#! /bin/sh


case "$1" in
start)
echo "Starting init script for I2C module"
modprobe i2c_bcm2835
modprobe i2c_dev
;;
stop)
echo "Removing user modules"
rmmod i2c_dev
rmmod i2c_bcm2835
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0

